In [5]:
import numpy as np
tmp=[1,2,3]
A=np.array([1,2,3])
B=np.array([4,3,0])
print('A+B',np.add(A,B))
print('A-B=',np.subtract(A,B)) 

A+B [5 5 3]
A-B= [-3 -1  3]


In [9]:
C = np.array([[1,2,3],  
              [1,1,1]])   #A*A 为A里面的每个元素乘以A的每个元素  #A@A  为A矩阵乘以A矩阵
D = np.array([[4,3,9,9],
              [1,1,2,2,],
              [4,2,1,1]])
print('np.dot(C,D)=',np.dot(C,D)) 
print('np.matmul(C,D)',np.matmul(C,D)) 
print('     C@D=   ',np.matmul(C,D))
print('np.multiply(D,D)=',np.multiply(D,D))
print('           D*D  =',D*D)

np.dot(C,D)= [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) [[18 11 16 16]
 [ 9  6 12 12]]
     C@D=    [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D)= [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
           D*D  = [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


In [10]:
t1 = np.array([1,2,3])
t2 = np.array([1,2,3])
print(np.dot(t1,t2))
print(np.matmul(t1,t2))
print(t1*t2)  #元素t1,t2的乘积

14
14
[1 4 9]
